### ISSUE TITLE
Ubuntu 22.04, unable to fetch the Copernicus data

### ISSUE THREAD

**Issue by lbarqueira** [milos-agathon/visualize-temperature-with-r#1]
Hi,
I have been trying to implement your solution. I have an issue on Ubuntu, that retrieves the following error:

Error : Client has not agreed to the required terms and conditions.http://copernicus-climate.eu/exc/missing-termsClient has not agreed to the required terms and conditions.list(required_terms = list(list(title = "Licence to use Copernicus Products", url = "https://cds.climate.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products", reason = "missing")))FALSEclient
Retrying Download

I had done all your steps. Could you please help me solve this issue?

Thanks
Luis Barqueira

**Comment by milos-agathon** [comment]
Hi Luis,
I found a short explanation of this error on the [CDS website](https://confluence.ecmwf.int/display/CKB/Common+Error+Messages+for+CDS+Requests). It appears that it happens in a small number of cases. There are two options:

- Go to the ADS [website](https://ads.atmosphere.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products), register, and accept the license terms 
- Install the latest version of the [CDS API](https://cds.climate.copernicus.eu/api-how-to)
Let me know how it goes.
Milos

**Comment by lbarqueira** [comment]
Thanks a lot, Milos, it solved my issue.

**Comment by lbarqueira** [comment]
Thanks, it's solved with your explanation.
