### ISSUE TITLE
How to read poland_2m_temperature.nc file once downloaded

### ISSUE THREAD

**Issue by lbarqueira** [milos-agathon/visualize-temperature-with-r#2]
Hi Milos,

once we download the poland_temp <- KrigR::download_ERA(...), if I do not want to download it again, but instead read it from the file  poland_2m_temperature.nc, and assign it to poland_temp, how can I do it?

Thanks again,

Luis

**Comment by milos-agathon** [comment]
Hi Luis,

Damn I should have included that part in my tutorial 😕. You can use `terra`:

`poland_temp <- terra::rast(poland_2m_temperature.nc)`

But be aware that the layer names will change. So instead of "X1" you might have something like this: "X1_poland_2m_temperature", i.e. Xn+filename.

**Comment by lbarqueira** [comment]
Hi Milo, thank you for your support.

Using your proposed solution, when I run poland_temp_nc <- terra::rast("poland_2m_temperature.nc") it gives the following warning:

In new_CppObject_xp(fields$.module, fields$.pointer, ...) :
  GDAL Message 1: dimension #0 (time) is not a Time or Vertical dimension.

Running head(poland_temp_nc):

Warning message:
In x@ptr$extractCell(i - 1) :
  GDAL Message 1: dimension #0 (time) is not a Time or Vertical dimension.


Looking forward to hearing from you.

Thanks,
Luis

**Comment by milos-agathon** [comment]
Hi Luis,

That's really annoying and I suspect of package control issues. Can you run `sessionInfo()` in R and paste your output here. I'd like to compare our package versions.

Best regards,
Milos

**Comment by lbarqueira** [comment]
Hi Milos, sure.


![session](https://github.com/milos-agathon/visualize-temperature-with-r/assets/65919567/73176027-599e-4015-b97b-59436f21983f)

**Comment by milos-agathon** [comment]
Hi Luis,

My terra is `terra_1.6-53`. Also, my rgdal is `rgdal_1.5-23`.
Could you try to install my terra version first and then check if the code successfully runs? 
If not, you could as a next step also install my version of rgdal.

Let me know how it goes.
Milos

**Comment by lbarqueira** [comment]
Hi Milos, I tried, and still not working.

Meanwhile, I installed the package raster and used the brick() method. It seems to work.

poland_temp <- raster::brick(poland_2m_temperature.nc)

It can resolve the RasterBrick and recognize all the layers.

I appreciate all the support you are giving. 

Thank you very much,

Luis

**Comment by lbarqueira** [comment]
Thanks, Milos for all the support.
